---
title: "Multi Site Monte Carlo"
output: pdf_document
---

# imports

```{r, warning=FALSE}
library(MASS)
library(parallel)

source("ArtfimaCausal.R")
source("MultiStateSpaceFunctions.R")
source("Data_Creation_Funcs.R")

n_cores <- detectCores() - 1
```

# MCMC function

```{r}
mc_one_run <- function(i, true_theta, start_vals, T_len, n_side, m, lower, upper) {
  
  # Simulate
  mat <- simulate_artfima_spatial(
    T_len = T_len,
    n_side = n_side,
    m = m,
    true_theta = true_theta
  )
  
  # Estimate
  fit <- tryCatch(
    nlminb(
      start = start_vals,
      objective = neg_loglik,
      data = mat,
      m = m,
      n_side = n_side,
      lower = lower,
      upper = upper
    ),
    error = function(e) return(NULL)
  )
  
  if (!is.null(fit) && fit$convergence == 0) {
    return(fit$par)
  } else {
    return(rep(NA, length(start_vals)))
  }
}

run_MCMC = function(cluster, true_theta, hat_theta, m, iter, n_side, T, lower = NULL, upper = NULL) {
  
  if (is.null(upper)) {
    bounds = get_bounds(hat_theta)
    lower = bounds$lower
    upper = bounds$upper
  }

  results_list <- parLapply(
    cluster,
    1:iter,
    mc_one_run,
    true_theta = true_theta,
    start_vals = hat_theta,
    T_len = T,
    n_side = n_side,
    m = m,
    lower = lower,
    upper = upper
  )
  
  
  estimates <- do.call(rbind, results_list)
  true_vec <- unlist(true_theta)[names(hat_theta)]
  
  mean_est <- colMeans(estimates, na.rm = TRUE)
  sd_est <- apply(estimates, 2, sd, na.rm = TRUE)
  
  bias <- mean_est - true_vec
  rel_bias <- ifelse(true_vec == 0, NA, bias / true_vec)
  
  mse <- colMeans(
    (estimates -
       matrix(true_vec,
              nrow = iter,
              ncol = length(true_vec),
              byrow = TRUE))^2,
    na.rm = TRUE
  )
  SqrtMSE = sqrt(mse)
  
  results <- rbind(
    True = true_vec,
    Mean = mean_est,
    sd = sd_est,
    RelBias = rel_bias,
    SqrtMSE = SqrtMSE,
    starting = hat_theta
  )
  
  return(round(results,4))
}

get_bounds <- function(hat_theta) {
  lower_template <- c(
    d        = -0.49,
    lambda   = 1e-6,
    phi      = -0.99,
    theta    = -0.99,
    sigma2_eta  = 1e-6,
    sigma2_w    = 1e-6,
    rho         = -0.99
  )
  
  upper_template <- c(
    d        = 0.49,
    lambda   = 5,
    phi      = 0.99,
    theta    = 0.99,
    sigma2_eta  = 10,
    sigma2_w    = 10,
    rho         = 0.99
  )

  lower <- lower_template[names(hat_theta)]
  upper <- upper_template[names(hat_theta)]
  list(lower = lower, upper = upper)
}

run_one_setting <- function(cluster, true_theta, hat_theta, 
                            m, iter, n_side, T_len) {
  
  cat("--------------------------------------------------\n")
  cat("Settings:\n")
  cat("T =", T_len, 
      " | n_side =", n_side,
      " | m =", m,
      " | iter =", iter, "\n\n")
  
  start_time <- Sys.time()
  
  results <- run_MCMC(cluster, true_theta, hat_theta, 
                      m, iter, n_side, T_len)
  
  end_time <- Sys.time()
  
  print(results)
  
  cat("\nRuntime:",
      round(difftime(end_time, start_time, units = "mins"), 2),
      "minutes\n\n")
}
```

# Run MCMC to file


```{r}
cluster <- makeCluster(n_cores)

clusterExport(cluster, ls())  # export all objects
clusterEvalQ(cluster, suppressMessages(library(MASS)))  # needed for mvrnorm

true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.3,
  theta = 0.3,
  sigma2_eta = 0.45,
  sigma2_w = 0,
  rho = 0.45
)

hat_theta <- c(
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.5,
  rho = 0.5
)

output_file <- "ARMA1.txt"
sink(output_file)

cat("Monte Carlo Study Results\n")
cat("===========================\n\n")
cat("Started at:", format(Sys.time()), "\n\n")

settings <- list(
  list(T_len = 25, n_side = 2, m = 5, iter = 3)
)

for (s in settings) {
  run_one_setting(cluster, true_theta, hat_theta,
                  m = s$m,
                  iter = s$iter,
                  n_side = s$n_side,
                  T_len = s$T_len)
}
stopCluster(cluster)

cat("Finished at:", format(Sys.time()), "\n")
sink()
```

# Run MCMC
```{r}
# set.seed(4562)
# 
# # -------------------------
# # Cluster settings
# # -------------------------
# cluster <- makeCluster(n_cores)
# 
# clusterExport(cluster, ls())  # export all objects
# clusterEvalQ(cluster, suppressMessages(library(MASS)))  # needed for mvrnorm
# 
# # -------------------------
# # Params
# # -------------------------
# true_theta <- list(
#   d = 0.15,
#   lambda = 0.05,
#   phi = 0.2,
#   theta = 0.45,
#   sigma2_eta = 1.5,
#   sigma2_w = 0,
#   rho = 0.55
# )
# 
# hat_theta <- c(
#   d = 0.3,
#   lambda=0.1,
#   phi = 0.5,
#   theta = 0.5,
#   sigma2_eta = 1,
#   rho = 5
# )
# 
# # -------------------------
# # MC settings
# # -------------------------
# n_side <- 5
# T_len <- 25
# m <- 5
# iter <- 10
# 
# start_time <- Sys.time()
# cat("Started at:", format(start_time), "\n")
# 
# run_MCMC(cluster, true_theta, hat_theta, m, iter, n_side, T_len)
# 
# stopCluster(cluster)
# 
# end_time <- Sys.time()
# cat("Finished at:", format(end_time), "\n")
# cat("Parameters are: T:", T_len, "n_side: ", n_side, "m: ", m, "iter: ", iter)
# 
# cat(" Total time:", round(difftime(end_time, start_time, units = "mins"), 2), "minutes\n")
```


Next time:
in dpeth on spectral papers

