---
title: "Speed Testing"
output: pdf_document
---

```{r}
library(MASS)
library(parallel)

source("ArtfimaCausal.R")
source("MultiStateSpaceFunctions.R")
source("Data_Creation_Funcs.R")
```

```{r}
# -------------------------
# Params
# -------------------------
true_theta <- list(
  d = 0.15,
  lambda = 0.05,
  phi = 0.2,
  theta = 0.45,
  sigma2_eta = 1.5,
  sigma2_w = 0.000001,
  rho = 0.55
)

theta <- list(
  d = 0.3,
  lambda=0.1,
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 1,
  sigma2_w = 0.000001,
  rho = 5
)

# -------------------------
# MC settings
# -------------------------
n_side <- 10
T_len <- 250
m <- 10

start_time <- Sys.time()
cat("Started at:", format(start_time), "\n")

# STEP 1: Data Creation

mat <- simulate_artfima_spatial(
  T_len = T_len,
  n_side = n_side,
  m = m,
  true_theta = true_theta
)
data = mat

# STEP 2: CAUSAL ESTIMATION 

  # ---- Build psi (temporal structure) ----
  psi <- psi_artfima(
    m = m,
    d = theta$d,
    lambda = theta$lambda,
    ar = theta$phi,
    ma = theta$theta
  )
  
  # ---- Build spatial covariance (Matérn ν = 1/2) ----
  n_loc = nrow(data)
  if (n_loc == 1) {
    
    # Univariate case
    Sigma_eta <- matrix(theta$sigma2_eta, 1, 1)
    
  } else {
    
    # Multivariate spatial case
    if (is.na(theta$rho) || theta$rho <= 0)
      return(1e12)
    
    coords <- expand.grid(x = 1:n_side, y = 1:n_side)
    coords <- as.matrix(coords)
    
    D <- as.matrix(dist(coords))
    
    Sigma_eta <- theta$sigma2_eta * exp(-D / theta$rho)
  }

# STEP 3: STATE SPACE CREATION
  # ---- Build state-space matrices ----
  state_space <- create_state_space(
    n_loc = nrow(data),
    m = m,
    sigma2_w = theta$sigma2_w,
    psi = psi,
    Sigma_eta = Sigma_eta
  )

# STEP 4: KALMAN FILTER
  # ---- Run Kalman filter ----
  lik <- kalman_filter(
    data = data,
    state_space = state_space,
    m = m
  )

end_time <- Sys.time()
cat("Finished at:", format(end_time), "\n")
cat("Parameters are: T:", T_len, "n_side: ", n_side, "m: ", m)

cat(" Total time:", round(difftime(end_time, start_time, units = "mins"), 2), "minutes\n")
```



