---
title: "KalmanFilterMatricesTests"
output: html_document
---

# Simulate Data
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

T_len = 250
m = 10
n_side = 10

print(peakRAM(simulate_artfima_spatial(T_len, n_side, m, true_theta)))
```

# Create State Space
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)
hat_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 250
m = 10
n_side = 10
n_loc = n_side^2
data <- simulate_artfima_spatial(
  T_len = T_len,
  n_side = n_side,
  m = m,
  true_theta = true_theta
)

coords <- expand.grid(x = 1:n_side, y = 1:n_side)
coords <- as.matrix(coords)

D <- as.matrix(dist(coords))
Sigma_eta <- hat_theta$sigma2_eta * exp(-D / hat_theta$rho)

psi <- psi_artfima(
  m = m,
  d = hat_theta$d,
  lambda = hat_theta$lambda,
  ar = hat_theta$phi,
  ma = hat_theta$theta
)

state_space = create_state_space(n_loc, m, psi, Sigma_eta, T_len)

# print(peakRAM(create_state_space(n_loc, m, psi, Sigma_eta, T_len)))
```

# predict Step
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 250
m = 10
n_side = 10
n_loc = n_side^2
state_dim <- (m + 1) * n_loc

X_t <- matrix(0, state_dim, 1)
Omega_t <- diag(500, state_dim)


coords <- expand.grid(x = 1:n_side, y = 1:n_side)
coords <- as.matrix(coords)

D <- as.matrix(dist(coords))
Sigma_eta <- hat_theta$sigma2_eta * exp(-D / hat_theta$rho)

psi <- psi_artfima(
  m = m,
  d = hat_theta$d,
  lambda = hat_theta$lambda,
  ar = hat_theta$phi,
  ma = hat_theta$theta
)

Y_first = matrix(0, nrow= n_loc, ncol = 1)

state_space = create_state_space(n_loc, m, psi, Sigma_eta, T_len)
pred = predict_step(X_t, Omega_t, state_space, Y_first)

if (sum(dim(pred$X_pred) == dim(X_t)) != 2) {
  stop("ERROR: X dimension out of sync")
}
if (sum(dim(pred$Omega_pred) == dim(Omega_t)) != 2) {
  stop("ERROR: Omega dimension out of sync")
}
```

# Update Step
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 250
m = 10
n_side = 10
n_loc = n_side^2
state_dim <- (m + 1) * n_loc

X_t <- matrix(0, state_dim, 1)
Omega_t <- diag(500, state_dim)
Y_first = matrix(0, nrow= n_loc, ncol = 1)


data = simulate_artfima_spatial(T_len, n_side, m, true_theta)


coords <- expand.grid(x = 1:n_side, y = 1:n_side)
coords <- as.matrix(coords)

D <- as.matrix(dist(coords))
Sigma_eta <- hat_theta$sigma2_eta * exp(-D / hat_theta$rho)

psi <- psi_artfima(
  m = m,
  d = hat_theta$d,
  lambda = hat_theta$lambda,
  ar = hat_theta$phi,
  ma = hat_theta$theta
)

state_space = create_state_space(n_loc, m, psi, Sigma_eta, T_len)
pred = predict_step(X_t, Omega_t, state_space, Y_first)

X_t = pred$X_pred
Omega_t = pred$Omega_pred


Y_obs <- matrix(data[, 1], ncol = 1) # choose a random column to continue the loop

update = update_step(state_space, X_t, Omega_t, Y_obs)

if (sum(dim(update$X_updated) == dim(X_t)) != 2) {
  stop("ERROR: X dimension out of sync")
}
if (sum(dim(update$Omega_updated) == dim(Omega_t)) != 2) {
  stop("ERROR: Omega dimension out of sync")
}
if (is.na(update$likeli)) { 
  stop("ERROR: Likeli not real!")
}
if (sum(dim(update$Y_pred) == dim(Y_obs)) != 2) {
  stop("ERROR: Omega dimension out of sync")
}
```

# Kalman Filter
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 250
m = 5
n_side = 5
n_loc = n_side^2
data <- simulate_artfima_spatial(
  T_len = T_len,
  n_side = n_side,
  m = m,
  true_theta = true_theta
)

coords <- expand.grid(x = 1:n_side, y = 1:n_side)
coords <- as.matrix(coords)

D <- as.matrix(dist(coords))
Sigma_eta <- hat_theta$sigma2_eta * exp(-D / hat_theta$rho)

psi <- psi_artfima(
  m = m,
  d = hat_theta$d,
  lambda = hat_theta$lambda,
  ar = hat_theta$phi,
  ma = hat_theta$theta
)

state_space = create_state_space(n_loc, m, psi, Sigma_eta, T_len)
likeli = kalman_filter(data, state_space)
print(likeli)

if (is.na(likeli)) { 
  stop("ERROR: Likeli not real!")
}
```

# Neg_loglik
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 50
m = 10
n_side = 10
n_loc = n_side^2
data <- simulate_artfima_spatial(
  T_len = T_len,
  n_side = n_side,
  m = m,
  true_theta = true_theta
)

coords <- expand.grid(x = 1:n_side, y = 1:n_side)
coords <- as.matrix(coords)

D <- as.matrix(dist(coords))

# par is the parameters

# par, data, m, n_side, D
neg_likeli = neg_loglik(hat_theta, data, m, D)

print(neg_likeli)
if (is.na(neg_likeli)) { 
  stop("ERROR: Likeli not real!")
}
```

# MC One Run
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
source("MatrixMCRuns.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 50
m = 5
n_side = 5

if (n_side > 1) {
  
  coords <- expand.grid(x = 1:n_side, y = 1:n_side)
  coords <- as.matrix(coords)
  
  D <- as.matrix(dist(coords))
} else {
  D <- null
}

bounds = get_bounds(hat_theta)
lower = bounds$lower
upper = bounds$upper
# i, true_theta, start_vals, T_len, n_side, m, lower, upper
print(unlist(true_theta)[names(hat_theta)])
mc_one_run(1, true_theta, hat_theta, T_len, n_side, m, lower, upper, D)

# print(peakRAM())
```


# MC test run
```{r}
rm(list=ls())
gc()
source("../Base Functions/ArtfimaCausal.R")
source("../Base Functions/Data_Creation_Funcs.R")
source("TestPredictFunction.R")
source("MatrixMCRuns.R")
library(peakRAM)
true_theta <- list(
  d = 0,
  lambda = 0,
  phi = 0.45,
  theta = 0.3,
  sigma2_eta = 0.5,
  sigma2_w = 0,
  rho = 0.35
)

hat_theta <- list(
  phi = 0.5,
  theta = 0.5,
  sigma2_eta = 0.75,
  rho = 0.5
)

T_len = 50
m = 5
n_side = 5
iter = 10

run_MC(true_theta, hat_theta, m, iter, n_side, T_len)
```





